//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "character")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::player_character::Entity")]
    PlayerCharacter,
}

impl Related<super::player_character::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerCharacter.def()
    }
}

impl Related<super::player::Entity> for Entity {
    fn to() -> RelationDef {
        super::player_character::Relation::Player.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::player_character::Relation::Character.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
