//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "player")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub account_id: i32,
    pub character_id: i64,
    pub name: String,
    pub language: i32,
    pub country: i32,
    pub selected_character_id: i32,
    pub selected_theme_id: i32,
    pub head_id: i32,
    pub title_id: i32,
    pub total_score: i32,
    pub total4k_score: i32,
    pub total6k_score: i32,
    pub total8k_score: i32,
    pub level: i32,
    pub current_exp: i32,
    pub maximum_exp: i32,
    pub total_arcade_score: i32,
    pub pre_rank: i32,
    pub pre_rank4k: i32,
    pub pre_rank6k: i32,
    pub pre_rank_param: i32,
    pub pre_rank4k_param: i32,
    pub pre_rank6k_param: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Account,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
