//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::account::Entity as Account;
pub use super::character::Entity as Character;
pub use super::daily_login::Entity as DailyLogin;
pub use super::player::Entity as Player;
pub use super::shop_item::Entity as ShopItem;
