//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "shop_item")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub item_id: i32,
    pub item_type: Option<String>,
    pub cost_type: i32,
    pub normal_price: i32,
    pub discount_price: i32,
    pub order: i32,
    pub begin_sale_time: i64,
    pub discount_begin_time: i64,
    pub discount_end_time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
