//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "theme")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::player::Entity")]
    Player,
    #[sea_orm(has_many = "super::player_theme::Entity")]
    PlayerTheme,
}

impl Related<super::player_theme::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayerTheme.def()
    }
}

impl Related<super::player::Entity> for Entity {
    fn to() -> RelationDef {
        super::player_theme::Relation::Player.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::player_theme::Relation::Theme.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
