//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use super::sea_orm_active_enums::BeatmapDifficulty;
use super::sea_orm_active_enums::BeatmapMode;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "score")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub beatmap_id: i32,
    pub player_id: i32,
    pub mode: BeatmapMode,
    pub difficulty: BeatmapDifficulty,
    pub finish_level: i32,
    pub score: i32,
    pub is_full_combo: bool,
    pub is_perfect: bool,
    pub miss_count: i32,
    pub submitted_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::beatmap::Entity",
        from = "Column::BeatmapId",
        to = "super::beatmap::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Beatmap,
    #[sea_orm(
        belongs_to = "super::player::Entity",
        from = "Column::PlayerId",
        to = "super::player::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Player,
}

impl Related<super::beatmap::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Beatmap.def()
    }
}

impl Related<super::player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Player.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
