//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "beatmap_difficulty")]
pub enum BeatmapDifficulty {
    #[sea_orm(string_value = "easy")]
    Easy,
    #[sea_orm(string_value = "hard")]
    Hard,
    #[sea_orm(string_value = "normal")]
    Normal,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "beatmap_kind")]
pub enum BeatmapKind {
    #[sea_orm(string_value = "dlc")]
    Dlc,
    #[sea_orm(string_value = "free")]
    Free,
    #[sea_orm(string_value = "sale")]
    Sale,
    #[sea_orm(string_value = "tutorial")]
    Tutorial,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "beatmap_mode")]
pub enum BeatmapMode {
    #[sea_orm(string_value = "eight_keys")]
    EightKeys,
    #[sea_orm(string_value = "four_keys")]
    FourKeys,
    #[sea_orm(string_value = "six_keys")]
    SixKeys,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "country")]
pub enum Country {
    #[sea_orm(string_value = "alien")]
    Alien,
    #[sea_orm(string_value = "asean")]
    Asean,
    #[sea_orm(string_value = "china")]
    China,
    #[sea_orm(string_value = "eu")]
    Eu,
    #[sea_orm(string_value = "hong_kong")]
    HongKong,
    #[sea_orm(string_value = "japan")]
    Japan,
    #[sea_orm(string_value = "macao")]
    Macao,
    #[sea_orm(string_value = "other")]
    Other,
    #[sea_orm(string_value = "south_korea")]
    SouthKorea,
    #[sea_orm(string_value = "tai_wan")]
    TaiWan,
    #[sea_orm(string_value = "united_kingdom")]
    UnitedKingdom,
    #[sea_orm(string_value = "united_states")]
    UnitedStates,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "language")]
pub enum Language {
    #[sea_orm(string_value = "china")]
    China,
    #[sea_orm(string_value = "english")]
    English,
    #[sea_orm(string_value = "japan")]
    Japan,
    #[sea_orm(string_value = "traditional")]
    Traditional,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "shop_item_type")]
pub enum ShopItemType {
    #[sea_orm(string_value = "character")]
    Character,
    #[sea_orm(string_value = "song")]
    Song,
    #[sea_orm(string_value = "theme")]
    Theme,
}
