//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use super::sea_orm_active_enums::ShopItemType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "shop_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub item_id: i32,
    pub item_type: ShopItemType,
    pub cost_type: i32,
    pub normal_price: i32,
    pub discount_price: i32,
    pub order: i32,
    pub begin_sale_time: DateTimeWithTimeZone,
    pub discount_begin_time: DateTimeWithTimeZone,
    pub discount_end_time: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
